version: '3'

volumes:
  postgres-data:
    driver: local
  postgres-db-data:
    driver: local

services:
  postgres-keycloak:
    image: postgres
    container_name: postgres-keycloak
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./keycloak-postgres.env
    ports:
      - 5445:5432
    networks:
      - keycloak-postgres-network

  keycloak:
    image: quay.io/keycloak/keycloak:19.0.1
    env_file:
      - ./keycloak-postgres.env
    entrypoint: /opt/keycloak/bin/kc.sh start-dev
    ports:
      - 8080:8080
    depends_on:
      - postgres-keycloak
    networks:
      - keycloak-postgres-network

  postgresql-db:
    image: postgres:14.1
    container_name: postgresql-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=my_db
    ports:
      - '5432:5432'
    volumes:
      - postgres-db-data:/var/lib/postgresql/data

networks:
  keycloak-postgres-network:
    driver: bridge
