server:
  port: 8082

spring:
  application:
    name: Api Gateway
  config:
    import:
      - classpath:routing.yaml


user-service:
  url: http://localhost:8081/
auth:
  url: http://localhost:8080/
  realm: IamTesterRealm
  client-id: api-gateway-client
  client-secret: G7hKLES7jcGqMWVhF5T27fGQd2bVfq4N

