server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/my_db
    username: admin
    password: root
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/my_db
    user: admin
    password: root
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/IamTesterRealm

logging:
  level:
    org:
      springframework:
        security: INFO

keycloak:
  realm: IamTesterRealm
  server-url: http://localhost:8080/
  client-id: user-service-client
  client-secret: aFLfjJaOwsIHZuKERK4A3ij3ogPBHu0K
