FROM eclipse-temurin:17-jdk-alpine
MAINTAINER semenovivan94@gmail.com
COPY target/user-service-0.0.1-SNAPSHOT.jar  user-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","user-service-0.0.1-SNAPSHOT.jar"]
